name: wallpaper_a_day
description: "A wallpaper app that changes your wallpaper every day."

publish_to: "none"

version: 0.2.12+16

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_acrylic: ^1.1.4
  macos_ui: 2.1.7
  elbe: ^0.2.8
  moewe: ^0.2.10
  http: ^1.2.2
  url_launcher: ^6.3.1
  html: ^0.15.5
  window_manager: ^0.5.1
  tray_manager: ^0.5.1
  image: ^4.5.4
  screen_retriever: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: NotesESA
      fonts:
        - asset: assets/notesesa_bold.otf

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/esawad_icon.png"
  macos:
    generate: true
    image_path: "assets/esawad_icon.png"
